services:
  auth-service:
    build:
      context: ./auth-service
    container_name: plantify-auth-service
    environment:
      SERVER_PORT: 8081
      JWT_ACCESS_TOKEN_EXPIRATION: 300000
      JWT_REFRESH_TOKEN_EXPIRATION: 86400000
      JWT_KEY_ID: plantify-local-rsa-key-1
    ports:
      - "8081:8081"

  demo-resource-service:
    build:
      context: .
      dockerfile: demo-resource-service/Dockerfile
    container_name: plantify-demo-resource-service
    environment:
      SERVER_PORT: 8082
      AUTH_JWK_SET_URI: http://auth-service:8081/.well-known/jwks.json
    ports:
      - "8082:8082"
    depends_on:
      - auth-service

  k6:
    image: grafana/k6:0.53.0
    profiles:
      - test
    environment:
      AUTH_URL: http://auth-service:8081
      RESOURCE_URL: http://demo-resource-service:8082
    volumes:
      - ./experiments/k6:/scripts
    depends_on:
      - auth-service
      - demo-resource-service
    entrypoint: ["k6"]
