server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: demo-resource-service

auth:
  validate-token-url: ${AUTH_VALIDATE_TOKEN_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
